services:
  noip-updater:
    build: .
    container_name: noip-updater
    restart: always
    environment:
      - UPDATE_INTERVAL=300
    volumes:
      - ./logs:/var/log
      - ./data:/app/data
    # Enable IPv6 networking
    networks:
      - ipv6_network
    secrets:
      - noip_username
      - noip_password
      - noip_hostname

networks:
  ipv6_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2001:db8:1::/64"
          gateway: "2001:db8:1::1"

volumes:
  logs:

secrets:
  noip_username:
    file: ./secrets/noip_username.txt
  noip_password:
    file: ./secrets/noip_password.txt
  noip_hostname:
    file: ./secrets/noip_hostname.txt
